# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/Alert.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSensorNearData/Alert.proto\x12\x0eSensorNearData\"S\n\x05\x41lert\x12\x1f\n\x10is_panic_braking\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x08latitude\x18\x02 \x01(\x01:\x01\x30\x12\x14\n\tlongitude\x18\x03 \x01(\x01:\x01\x30')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorNearData.Alert_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALERT._serialized_start=46
  _ALERT._serialized_end=129
# @@protoc_insertion_point(module_scope)
