# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/IndicatorRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from SensorNearData import header_pb2 as SensorNearData_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SensorNearData/IndicatorRequest.proto\x12\x0eSensorNearData\x1a\x1bSensorNearData/header.proto\"\xc2\x01\n\x10IndicatorRequest\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.SensorNearData.Header\x12\x45\n\x11indicator_request\x18\x02 \x01(\x0e\x32*.SensorNearData.IndicatorRequest.Indicator\"?\n\tIndicator\x12\n\n\x06IS_OFF\x10\x00\x12\x0b\n\x07IS_LEFT\x10\x01\x12\x0c\n\x08IS_RIGHT\x10\x02\x12\x0b\n\x07IS_BOTH\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorNearData.IndicatorRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INDICATORREQUEST._serialized_start=87
  _INDICATORREQUEST._serialized_end=281
  _INDICATORREQUEST_INDICATOR._serialized_start=218
  _INDICATORREQUEST_INDICATOR._serialized_end=281
# @@protoc_insertion_point(module_scope)
